-- HISTORICAL / NO-OP: private-read cutover is now included in
-- migrations/202609300002_provider_profiles_public_allowlist.sql.
-- Apply the complete migration rather than a separate deferred cutover.
-- Kept only to identify the retired two-phase rollout; no SQL remains here.
